spring.datasource.url=jdbc:mysql://localhost:3306/mastercontrol_training
spring.datasource.username=root
spring.datasource.password=Saurabhgiri667

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true